# Generated by Django 4.0.3 on 2022-03-19 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pets', '0003_petimage_alter_pet_type_pet_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photos',
        ),
        migrations.AddField(
            model_name='petimage',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app_pets.pet'),
        ),
    ]
