# Generated by Django 4.0.3 on 2022-03-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pets', '0004_remove_pet_photos_petimage_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
